#!/usr/bin/env bash
# Publish this port's generated C so CI can build the game without a ROM.
#
# Run it after a local regen against your own verified ROM:
#   bash tools/regen.sh
#   bash tools/publish_ci_src_gen.sh            # push to the assets repo
#   bash tools/publish_ci_src_gen.sh --dry-run  # build the archive only
#
# What is published is recompiler OUTPUT — src/gen/*.c plus recomp/funcs.h,
# which the build needs and .gitignore keeps out of this repo. The ROM itself
# is never uploaded anywhere.
#
# recomp/funcs.h matters as much as src/gen: it is generated by the same run
# and the game does not compile without it, so an archive carrying only
# src/gen fails in CI at the first translation unit.
#
# The implementation lives in the framework (one copy for every SNES port);
# this wrapper only supplies this game's repo, path, and file set.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

IMPL="snesrecomp/tools/ci/publish_src_gen.sh"
if [ ! -f "$IMPL" ]; then
  echo "publish_ci_src_gen.sh: $IMPL missing — run:" >&2
  echo "  git submodule update --init --recursive" >&2
  exit 1
fi

# Keep these three in step with .github/workflows/release.yml (SRC_GEN_REPO,
# SRC_GEN_ASSET) — the workflow fetches exactly what this publishes.
ASSETS_REPO="${CI_SRC_GEN_REPO:-TechnicallyComputers/psxrecomp-ci-assets}"
ASSETS_DIR="${CI_SRC_GEN_DIR:-gundamwing}"

exec bash "$IMPL" \
  --repo "$ASSETS_REPO" \
  --path "$ASSETS_DIR" \
  --include src/gen \
  --include recomp/funcs.h \
  "$@"
